name: Docker Image CI

on:
  push:
    branches: [ "portainer" ]
  pull_request:
    branches: [ "portainer" ]

jobs:

  CI-DEV:

    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        ref: portainer

    - name:  test env DEV
      env:
        TRAEFIK_USER_DASH: ${{ secrets.TRAEFIK_USER_DASH }}
        TRAEFIK_PWD_DASH: ${{ secrets.TRAEFIK_PWD_DASH }}
      run: |
        echo "$TRAEFIK_USER_DASH"
        echo "$TRAEFIK_PWD_DASH"
      
    - name: autenticate dokcer register
      uses: docker/login-action@v3.0.0
      with:
        username: ${{secrets.DOCKERHUB_USER}}
        password: ${{secrets.DOCKERHUB_PWD}}
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.0.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ceievfa/site-static:dev-0.${{github.run_number}}
          ceievfa/site-static:dev-latest
