name: Docker Image CI

on:
  push:
    branches: [ "portainer" ]
  pull_request:
    branches: [ "portainer" ]

jobs:

  CI_CD-DEV:

    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        ref: portainer

    - name: autenticate dokcer register
      uses: docker/login-action@v3.0.0
      with:
        username: ${{secrets.DOCKERHUB_USER}}
        password: ${{secrets.DOCKERHUB_PWD}}
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.0.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ceievfa/site-static:dev-0.${{github.run_number}}
          ceievfa/site-static:dev-latest
    
    - name:  Build compose Vars
      run: bash .github/scripts/build_compose_vars.sh
      env:
        TRAEFIK_USER_DASH: ${{ secrets.TRAEFIK_USER_DASH }}
        TRAEFIK_PWD_DASH: ${{ secrets.TRAEFIK_PWD_DASH }}
        TRAEFIK_MAIL: ${{ secrets.TRAEFIK_MAIL }}
      
    # - id: ssh
    #   uses: invi5H/ssh-action@v1
    #   with:
    #     SSH_HOST: ${{ secrets.SSH_HOST }}
    #     SSH_PORT: ${{ secrets.SSH_PORT }}
    #     SSH_USER: ${{ secrets.SSH_USER }}
    #     SSH_KEY: ${{ secrets.SSH_KEY }}
    
    # - name: Copy project
    #   run: ssh ${{ steps.ssh.outputs.SERVER }} COMANDO
    
    - name: Continuous Delivery
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      with:
        host: ${{ secrets.SSH_HOST }}
        user: ${{ secrets.SSH_USER }}
        # pass: ${{ secrets.SSH_PASS }}
        key: ${{ secrets.SSH_KEY }}
        first_ssh: |
          test -d /app/cicd && true || mkdir -p /app/cicd
          test -e /app/cicd/docker-compose.yaml && rm -f /app/cicd/docker-compose.yaml || true
          test -e /app/cicd/start.sh && rm -f /app/cicd/start.sh || true
        scp: |
          ./docker-compose.yaml => /app/cicd/
          .github/scripts/start.sh => /app/cicd/
        last_ssh: |
          bash /app/cicd/start.sh
          docker ps
